<?xml version="1.0"?>
<!DOCTYPE mess [
<!ELEMENT mess (machine+)>
	<!ATTLIST mess build CDATA #IMPLIED>
	<!ELEMENT machine (description, year?, manufacturer, history?, biosset*, rom*, disk*, sample*, chip*, video?, sound?, input?, dipswitch*, driver?, device*, ramoption*)>
		<!ATTLIST machine name CDATA #REQUIRED>
		<!ATTLIST machine sourcefile CDATA #IMPLIED>
		<!ATTLIST machine runnable (yes|no) "yes">
		<!ATTLIST machine cloneof CDATA #IMPLIED>
		<!ATTLIST machine romof CDATA #IMPLIED>
		<!ATTLIST machine sampleof CDATA #IMPLIED>
		<!ELEMENT description (#PCDATA)>
		<!ELEMENT year (#PCDATA)>
		<!ELEMENT manufacturer (#PCDATA)>
		<!ELEMENT history (#PCDATA)>
		<!ELEMENT biosset EMPTY>
			<!ATTLIST biosset name CDATA #REQUIRED>
			<!ATTLIST biosset description CDATA #REQUIRED>
			<!ATTLIST biosset default (yes|no) "no">
		<!ELEMENT rom EMPTY>
			<!ATTLIST rom name CDATA #REQUIRED>
			<!ATTLIST rom bios CDATA #IMPLIED>
			<!ATTLIST rom size CDATA #REQUIRED>
			<!ATTLIST rom crc CDATA #IMPLIED>
			<!ATTLIST rom md5 CDATA #IMPLIED>
			<!ATTLIST rom sha1 CDATA #IMPLIED>
			<!ATTLIST rom merge CDATA #IMPLIED>
			<!ATTLIST rom region CDATA #IMPLIED>
			<!ATTLIST rom offset CDATA #IMPLIED>
			<!ATTLIST rom status (baddump|nodump|good) "good">
			<!ATTLIST rom dispose (yes|no) "no">
		<!ELEMENT disk EMPTY>
			<!ATTLIST disk name CDATA #REQUIRED>
			<!ATTLIST disk md5 CDATA #IMPLIED>
			<!ATTLIST disk sha1 CDATA #IMPLIED>
			<!ATTLIST disk merge CDATA #IMPLIED>
			<!ATTLIST disk region CDATA #IMPLIED>
			<!ATTLIST disk index CDATA #IMPLIED>
			<!ATTLIST disk status (baddump|nodump|good) "good">
		<!ELEMENT sample EMPTY>
			<!ATTLIST sample name CDATA #REQUIRED>
		<!ELEMENT chip EMPTY>
			<!ATTLIST chip name CDATA #REQUIRED>
			<!ATTLIST chip type (cpu|audio) #REQUIRED>
			<!ATTLIST chip clock CDATA #IMPLIED>
		<!ELEMENT video EMPTY>
			<!ATTLIST video screen (raster|vector) #REQUIRED>
			<!ATTLIST video orientation (vertical|horizontal) #REQUIRED>
			<!ATTLIST video width CDATA #IMPLIED>
			<!ATTLIST video height CDATA #IMPLIED>
			<!ATTLIST video aspectx CDATA #IMPLIED>
			<!ATTLIST video aspecty CDATA #IMPLIED>
			<!ATTLIST video refresh CDATA #REQUIRED>
		<!ELEMENT sound EMPTY>
			<!ATTLIST sound channels CDATA #REQUIRED>
		<!ELEMENT input EMPTY>
			<!ATTLIST input service (yes|no) "no">
			<!ATTLIST input tilt (yes|no) "no">
			<!ATTLIST input players CDATA #REQUIRED>
			<!ATTLIST input control CDATA #IMPLIED>
			<!ATTLIST input buttons CDATA #IMPLIED>
			<!ATTLIST input coins CDATA #IMPLIED>
		<!ELEMENT dipswitch (dipvalue*)>
			<!ATTLIST dipswitch name CDATA #REQUIRED>
			<!ELEMENT dipvalue EMPTY>
				<!ATTLIST dipvalue name CDATA #REQUIRED>
				<!ATTLIST dipvalue default (yes|no) "no">
		<!ELEMENT driver EMPTY>
			<!ATTLIST driver status (good|imperfect|preliminary) #REQUIRED>
			<!ATTLIST driver emulation (good|imperfect|preliminary) #REQUIRED>
			<!ATTLIST driver color (good|imperfect|preliminary) #REQUIRED>
			<!ATTLIST driver sound (good|imperfect|preliminary) #REQUIRED>
			<!ATTLIST driver graphic (good|imperfect|preliminary) #REQUIRED>
			<!ATTLIST driver cocktail (good|imperfect|preliminary) #IMPLIED>
			<!ATTLIST driver protection (good|imperfect|preliminary) #IMPLIED>
			<!ATTLIST driver savestate (supported|unsupported) #REQUIRED>
			<!ATTLIST driver palettesize CDATA #REQUIRED>
		<!ELEMENT device (instance*, extension*)>
			<!ATTLIST device type CDATA #REQUIRED>
			<!ATTLIST device tag CDATA #IMPLIED>
			<!ATTLIST device mandatory CDATA #IMPLIED>
			<!ELEMENT instance EMPTY>
				<!ATTLIST instance name CDATA #REQUIRED>
				<!ATTLIST instance briefname CDATA #REQUIRED>
			<!ELEMENT extension EMPTY>
				<!ATTLIST extension name CDATA #REQUIRED>
		<!ELEMENT ramoption (#PCDATA)>
]>

<mess build="0.106 (Dec  4 2016)">
	<machine name="a2600" sourcefile="a2600.c">
		<description>Atari 2600 (NTSC)</description>
		<year>1977</year>
		<manufacturer>Atari</manufacturer>
		<chip type="cpu" name="M6502" clock="1194720"/>
		<chip type="audio" name="TIA" clock="31400"/>
		<video screen="raster" orientation="horizontal" width="160" height="226" aspectx="4" aspecty="3" refresh="60.000000"/>
		<sound channels="1"/>
		<input players="4" control="paddle" buttons="1"/>
		<dipswitch name="TV Type">
			<dipvalue name="Color" default="yes"/>
			<dipvalue name="B&amp;W"/>
		</dipswitch>
		<dipswitch name="Left Diff. Switch">
			<dipvalue name="A"/>
			<dipvalue name="B" default="yes"/>
		</dipswitch>
		<dipswitch name="Right Diff. Switch">
			<dipvalue name="A"/>
			<dipvalue name="B" default="yes"/>
		</dipswitch>
		<driver status="good" emulation="good" color="good" sound="good" graphic="good" savestate="unsupported" palettesize="128"/>
		<device type="cartridge" mandatory="1">
			<instance name="cartridge" briefname="cart"/>
			<extension name="bin"/>
			<extension name="a26"/>
		</device>
	</machine>
	<machine name="a5200" sourcefile="atari.c">
		<description>Atari 5200</description>
		<year>1982</year>
		<manufacturer>Atari</manufacturer>
		<rom name="5200.rom" size="2048" crc="4248d3e3" sha1="6ad7a1e8c9fad486fbec9498cb48bf5bc3adc530" region="cpu1" offset="f800"/>
		<chip type="cpu" name="M6510" clock="1789790"/>
		<chip type="audio" name="POKEY" clock="1789790"/>
		<video screen="raster" orientation="horizontal" width="336" height="225" aspectx="4" aspecty="3" refresh="59.923328"/>
		<sound channels="1"/>
		<input players="4" control="stick" buttons="2"/>
		<driver status="good" emulation="good" color="good" sound="good" graphic="good" savestate="unsupported" palettesize="256"/>
		<device type="cartridge">
			<instance name="cartridge" briefname="cart"/>
			<extension name="rom"/>
			<extension name="bin"/>
			<extension name="a52"/>
		</device>
		<ramoption>16384</ramoption>
	</machine>
	<machine name="a5200a" sourcefile="atari.c" cloneof="a5200" romof="a5200">
		<description>Atari 5200 (alt)</description>
		<year>1982</year>
		<manufacturer>Atari</manufacturer>
		<rom name="5200a.rom" size="2048" crc="c2ba2613" sha1="1d2a3f00109d75d2d79fecb565775eb95b7d04d5" region="cpu1" offset="f800"/>
		<chip type="cpu" name="M6510" clock="1789790"/>
		<chip type="audio" name="POKEY" clock="1789790"/>
		<video screen="raster" orientation="horizontal" width="336" height="225" aspectx="4" aspecty="3" refresh="59.923328"/>
		<sound channels="1"/>
		<input players="4" control="stick" buttons="2"/>
		<driver status="good" emulation="good" color="good" sound="good" graphic="good" savestate="unsupported" palettesize="256"/>
		<device type="cartridge">
			<instance name="cartridge" briefname="cart"/>
			<extension name="rom"/>
			<extension name="bin"/>
			<extension name="a52"/>
		</device>
		<ramoption>16384</ramoption>
	</machine>
	<machine name="a7800" sourcefile="a7800.c">
		<description>Atari 7800 NTSC</description>
		<year>1986</year>
		<manufacturer>Atari</manufacturer>
		<rom name="7800.rom" size="4096" crc="5d13730c" sha1="d9d134bb6b36907c615a594cc7688f7bfcef5b43" region="cpu1" offset="f000"/>
		<chip type="cpu" name="M6502" clock="1789772"/>
		<chip type="audio" name="TIA" clock="31400"/>
		<chip type="audio" name="POKEY" clock="1789772"/>
		<video screen="raster" orientation="horizontal" width="320" height="225" aspectx="4" aspecty="3" refresh="60.000000"/>
		<sound channels="1"/>
		<input players="2" control="joy8way" buttons="2"/>
		<dipswitch name="Left Diff. Switch">
			<dipvalue name="A"/>
			<dipvalue name="B" default="yes"/>
		</dipswitch>
		<dipswitch name="Right Diff. Switch">
			<dipvalue name="A"/>
			<dipvalue name="B" default="yes"/>
		</dipswitch>
		<driver status="good" emulation="good" color="good" sound="good" graphic="good" savestate="unsupported" palettesize="256"/>
		<device type="cartridge" mandatory="1">
			<instance name="cartridge" briefname="cart"/>
			<extension name="a78"/>
		</device>
	</machine>
	<machine name="a7800p" sourcefile="a7800.c" cloneof="a7800" romof="a7800">
		<description>Atari 7800 PAL</description>
		<year>1986</year>
		<manufacturer>Atari</manufacturer>
		<rom name="7800pal.rom" size="16384" crc="d5b61170" sha1="5a140136a16d1d83e4ff32a19409ca376a8df874" region="cpu1" offset="c000"/>
		<chip type="cpu" name="M6502" clock="1773447"/>
		<chip type="audio" name="TIA" clock="31400"/>
		<chip type="audio" name="POKEY" clock="1773447"/>
		<video screen="raster" orientation="horizontal" width="320" height="226" aspectx="4" aspecty="3" refresh="50.000000"/>
		<sound channels="1"/>
		<input players="2" control="joy8way" buttons="2"/>
		<dipswitch name="Left Diff. Switch">
			<dipvalue name="A"/>
			<dipvalue name="B" default="yes"/>
		</dipswitch>
		<dipswitch name="Right Diff. Switch">
			<dipvalue name="A"/>
			<dipvalue name="B" default="yes"/>
		</dipswitch>
		<driver status="good" emulation="good" color="good" sound="good" graphic="good" savestate="unsupported" palettesize="256"/>
		<device type="cartridge" mandatory="1">
			<instance name="cartridge" briefname="cart"/>
			<extension name="a78"/>
		</device>
	</machine>
	<machine name="lynx" sourcefile="lynx.c">
		<description>Lynx</description>
		<year>1989</year>
		<manufacturer>Atari</manufacturer>
		<rom name="lynx.bin" size="512" crc="e1ffecb6" sha1="de60f2263851bbe10e5801ef8f6c357a4bc077e6" region="cpu1" offset="0"/>
		<chip type="cpu" name="M65SC02" clock="4000000"/>
		<chip type="audio" name="Custom"/>
		<video screen="raster" orientation="horizontal" width="160" height="102" aspectx="4" aspecty="3" refresh="30.000000"/>
		<sound channels="1"/>
		<input players="1" control="joy8way" buttons="2"/>
		<dipswitch name="90 Degree Rotation">
			<dipvalue name="Counterclockwise"/>
			<dipvalue name="Clockwise"/>
			<dipvalue name="None"/>
			<dipvalue name="Crcfile" default="yes"/>
		</dipswitch>
		<driver status="preliminary" emulation="preliminary" color="good" sound="imperfect" graphic="good" savestate="unsupported" palettesize="4096"/>
		<device type="cartridge">
			<instance name="cartridge" briefname="cart"/>
			<extension name="lnx"/>
		</device>
		<device type="quickload">
			<instance name="quickload" briefname="quik"/>
			<extension name="o"/>
		</device>
	</machine>
	<machine name="lynxa" sourcefile="lynx.c" cloneof="lynx" romof="lynx">
		<description>Lynx (alternate rom save!)</description>
		<year>1989</year>
		<manufacturer>Atari</manufacturer>
		<rom name="lynxa.bin" size="512" crc="0d973c9d" sha1="e4ed47fae31693e016b081c6bda48da5b70d7ccb" region="cpu1" offset="0"/>
		<chip type="cpu" name="M65SC02" clock="4000000"/>
		<chip type="audio" name="Custom"/>
		<video screen="raster" orientation="horizontal" width="160" height="102" aspectx="4" aspecty="3" refresh="30.000000"/>
		<sound channels="1"/>
		<input players="1" control="joy8way" buttons="2"/>
		<dipswitch name="90 Degree Rotation">
			<dipvalue name="Counterclockwise"/>
			<dipvalue name="Clockwise"/>
			<dipvalue name="None"/>
			<dipvalue name="Crcfile" default="yes"/>
		</dipswitch>
		<driver status="preliminary" emulation="preliminary" color="good" sound="imperfect" graphic="good" savestate="unsupported" palettesize="4096"/>
		<device type="cartridge">
			<instance name="cartridge" briefname="cart"/>
			<extension name="lnx"/>
		</device>
		<device type="quickload">
			<instance name="quickload" briefname="quik"/>
			<extension name="o"/>
		</device>
	</machine>
	<machine name="lynx2" sourcefile="lynx.c" cloneof="lynx" romof="lynx">
		<description>Lynx II</description>
		<year>1991</year>
		<manufacturer>Atari</manufacturer>
		<rom name="lynx2.bin" size="512" region="cpu1" status="nodump" offset="0"/>
		<chip type="cpu" name="M65SC02" clock="4000000"/>
		<chip type="audio" name="Custom"/>
		<chip type="audio" name="Custom"/>
		<video screen="raster" orientation="horizontal" width="160" height="102" aspectx="4" aspecty="3" refresh="30.000000"/>
		<sound channels="3"/>
		<input players="1" control="joy8way" buttons="2"/>
		<dipswitch name="90 Degree Rotation">
			<dipvalue name="Counterclockwise"/>
			<dipvalue name="Clockwise"/>
			<dipvalue name="None"/>
			<dipvalue name="Crcfile" default="yes"/>
		</dipswitch>
		<driver status="preliminary" emulation="preliminary" color="good" sound="imperfect" graphic="good" savestate="unsupported" palettesize="4096"/>
		<device type="cartridge">
			<instance name="cartridge" briefname="cart"/>
			<extension name="lnx"/>
		</device>
		<device type="quickload">
			<instance name="quickload" briefname="quik"/>
			<extension name="o"/>
		</device>
	</machine>
	<machine name="jaguar" sourcefile="jaguar.c">
		<description>Atari Jaguar</description>
		<year>1993</year>
		<manufacturer>Atari</manufacturer>
		<rom name="jagboot.rom" size="131072" crc="fb731aaa" sha1="f8991b0c385f4e5002fa2a7e2f5e61e8c5213356" region="cpu1" offset="e00000"/>
		<chip type="cpu" name="68EC020" clock="13295000"/>
		<chip type="cpu" name="Jaguar GPU" clock="26000000"/>
		<chip type="cpu" name="Jaguar DSP" clock="26000000"/>
		<chip type="audio" name="DAC"/>
		<chip type="audio" name="DAC"/>
		<video screen="raster" orientation="horizontal" width="320" height="240" aspectx="4" aspecty="3" refresh="60.000000"/>
		<sound channels="2"/>
		<input players="2" control="joy8way" buttons="5"/>
		<driver status="preliminary" emulation="good" color="good" sound="imperfect" graphic="imperfect" protection="preliminary" savestate="unsupported" palettesize="65534"/>
		<device type="cartridge" mandatory="1">
			<instance name="cartridge" briefname="cart"/>
			<extension name="jag"/>
			<extension name="abs"/>
			<extension name="bin"/>
			<extension name="rom"/>
		</device>
		<device type="quickload">
			<instance name="quickload" briefname="quik"/>
			<extension name="bin"/>
		</device>
	</machine>
	<machine name="nes" sourcefile="nes.c">
		<description>Nintendo Entertainment System (NTSC)</description>
		<year>1985</year>
		<manufacturer>Nintendo</manufacturer>
		<chip type="cpu" name="N2A03" clock="1789772"/>
		<chip type="audio" name="N2A03" clock="1789772"/>
		<video screen="raster" orientation="horizontal" width="256" height="240" aspectx="4" aspecty="3" refresh="59.940060"/>
		<sound channels="1"/>
		<input players="4" control="paddle" buttons="3"/>
		<driver status="good" emulation="good" color="good" sound="good" graphic="good" savestate="unsupported" palettesize="512"/>
		<device type="cartridge" mandatory="1">
			<instance name="cartridge" briefname="cart"/>
			<extension name="nes"/>
		</device>
	</machine>
	<machine name="nespal" sourcefile="nes.c" cloneof="nes" romof="nes">
		<description>Nintendo Entertainment System (PAL)</description>
		<year>1987</year>
		<manufacturer>Nintendo</manufacturer>
		<chip type="cpu" name="N2A03" clock="1773447"/>
		<chip type="audio" name="N2A03" clock="1773447"/>
		<video screen="raster" orientation="horizontal" width="256" height="240" aspectx="4" aspecty="3" refresh="50.000000"/>
		<sound channels="1"/>
		<input players="4" control="paddle" buttons="3"/>
		<driver status="good" emulation="good" color="good" sound="good" graphic="good" savestate="unsupported" palettesize="512"/>
		<device type="cartridge" mandatory="1">
			<instance name="cartridge" briefname="cart"/>
			<extension name="nes"/>
		</device>
	</machine>
	<machine name="famicom" sourcefile="nes.c">
		<description>Famicom</description>
		<year>1983</year>
		<manufacturer>Nintendo</manufacturer>
		<rom name="disksys.rom" size="8192" crc="5e607dcf" sha1="57fe1bdee955bb48d357e463ccbf129496930b62" region="cpu1" offset="e000"/>
		<chip type="cpu" name="N2A03" clock="1789772"/>
		<chip type="audio" name="N2A03" clock="1789772"/>
		<video screen="raster" orientation="horizontal" width="256" height="240" aspectx="4" aspecty="3" refresh="59.940060"/>
		<sound channels="1"/>
		<input players="4" control="paddle" buttons="3"/>
		<driver status="preliminary" emulation="preliminary" color="good" sound="good" graphic="good" savestate="unsupported" palettesize="512"/>
		<device type="cartridge">
			<instance name="cartridge" briefname="cart"/>
			<extension name="nes"/>
		</device>
		<device type="floppydisk">
			<instance name="floppydisk" briefname="flop"/>
			<extension name="dsk"/>
			<extension name="fds"/>
		</device>
	</machine>
	<machine name="famitwin" sourcefile="nes.c" cloneof="famicom" romof="famicom">
		<description>Famicom Twin</description>
		<year>1986</year>
		<manufacturer>Sharp</manufacturer>
		<rom name="disksys.rom" size="8192" crc="4df24a6c" sha1="e4e41472c454f928e53eb10e0509bf7d1146ecc1" region="cpu1" offset="e000"/>
		<chip type="cpu" name="N2A03" clock="1789772"/>
		<chip type="audio" name="N2A03" clock="1789772"/>
		<video screen="raster" orientation="horizontal" width="256" height="240" aspectx="4" aspecty="3" refresh="59.940060"/>
		<sound channels="1"/>
		<input players="4" control="paddle" buttons="3"/>
		<driver status="preliminary" emulation="preliminary" color="good" sound="good" graphic="good" savestate="unsupported" palettesize="512"/>
		<device type="cartridge">
			<instance name="cartridge" briefname="cart"/>
			<extension name="nes"/>
		</device>
		<device type="floppydisk">
			<instance name="floppydisk" briefname="flop"/>
			<extension name="dsk"/>
			<extension name="fds"/>
		</device>
	</machine>
	<machine name="gameboy" sourcefile="gb.c">
		<description>GameBoy</description>
		<year>1990</year>
		<manufacturer>Nintendo</manufacturer>
		<rom name="dmg_boot.bin" size="256" crc="59c8598e" sha1="4ed31ec6b0b175bb109c0eb5fd3d193da823339f" region="cpu1" offset="0"/>
		<chip type="cpu" name="Z80GB" clock="4194304"/>
		<chip type="audio" name="Custom"/>
		<video screen="raster" orientation="horizontal" width="160" height="144" aspectx="4" aspecty="3" refresh="59.732155"/>
		<sound channels="2"/>
		<input players="1" control="joy8way" buttons="2"/>
		<driver status="good" emulation="good" color="good" sound="good" graphic="good" savestate="unsupported" palettesize="4"/>
		<device type="cartridge">
			<instance name="cartridge" briefname="cart"/>
			<extension name="gb"/>
			<extension name="gmb"/>
			<extension name="cgb"/>
			<extension name="gbc"/>
			<extension name="sgb"/>
		</device>
	</machine>
	<machine name="supergb" sourcefile="gb.c">
		<description>Super GameBoy</description>
		<year>1994</year>
		<manufacturer>Nintendo</manufacturer>
		<chip type="cpu" name="Z80GB" clock="4295454"/>
		<chip type="audio" name="Custom"/>
		<video screen="raster" orientation="horizontal" width="256" height="224" aspectx="4" aspecty="3" refresh="59.732155"/>
		<sound channels="2"/>
		<input players="1" control="joy8way" buttons="2"/>
		<driver status="good" emulation="good" color="good" sound="good" graphic="good" savestate="unsupported" palettesize="32768"/>
		<device type="cartridge" mandatory="1">
			<instance name="cartridge" briefname="cart"/>
			<extension name="gb"/>
			<extension name="gmb"/>
			<extension name="cgb"/>
			<extension name="gbc"/>
			<extension name="sgb"/>
		</device>
	</machine>
	<machine name="gbpocket" sourcefile="gb.c" cloneof="gameboy" romof="gameboy">
		<description>GameBoy Pocket</description>
		<year>1996</year>
		<manufacturer>Nintendo</manufacturer>
		<chip type="cpu" name="Z80GB" clock="4194304"/>
		<chip type="audio" name="Custom"/>
		<video screen="raster" orientation="horizontal" width="160" height="144" aspectx="4" aspecty="3" refresh="59.732155"/>
		<sound channels="2"/>
		<input players="1" control="joy8way" buttons="2"/>
		<driver status="good" emulation="good" color="good" sound="good" graphic="good" savestate="unsupported" palettesize="4"/>
		<device type="cartridge" mandatory="1">
			<instance name="cartridge" briefname="cart"/>
			<extension name="gb"/>
			<extension name="gmb"/>
			<extension name="cgb"/>
			<extension name="gbc"/>
			<extension name="sgb"/>
		</device>
	</machine>
	<machine name="gbcolor" sourcefile="gb.c">
		<description>GameBoy Color</description>
		<year>1998</year>
		<manufacturer>Nintendo</manufacturer>
		<chip type="cpu" name="Z80GB" clock="4194304"/>
		<chip type="audio" name="Custom"/>
		<video screen="raster" orientation="horizontal" width="160" height="144" aspectx="4" aspecty="3" refresh="59.732155"/>
		<sound channels="2"/>
		<input players="1" control="joy8way" buttons="2"/>
		<driver status="good" emulation="good" color="good" sound="good" graphic="good" savestate="unsupported" palettesize="32768"/>
		<device type="cartridge" mandatory="1">
			<instance name="cartridge" briefname="cart"/>
			<extension name="gb"/>
			<extension name="gmb"/>
			<extension name="cgb"/>
			<extension name="gbc"/>
			<extension name="sgb"/>
		</device>
	</machine>
	<machine name="snes" sourcefile="snes.c">
		<description>Super Nintendo Entertainment System (NTSC)</description>
		<year>1989</year>
		<manufacturer>Nintendo</manufacturer>
		<rom name="spc700.rom" size="64" crc="44bb3a40" sha1="97e352553e94242ae823547cd853eecda55c20f0" region="user5" offset="0"/>
		<rom name="dsp1data.bin" size="2048" crc="4b02d66d" sha1="1534f4403d2a0f68ba6e35186fe7595d33de34b1" region="user6" offset="0"/>
		<chip type="cpu" name="G65C816" clock="3580000"/>
		<chip type="cpu" name="SPC700" clock="1024000"/>
		<chip type="audio" name="Custom"/>
		<video screen="raster" orientation="horizontal" width="512" height="240" aspectx="4" aspecty="3" refresh="60.000000"/>
		<sound channels="2"/>
		<input players="4" control="joy8way" buttons="6"/>
		<driver status="imperfect" emulation="good" color="good" sound="imperfect" graphic="imperfect" savestate="unsupported" palettesize="32768"/>
		<device type="cartridge" mandatory="1">
			<instance name="cartridge" briefname="cart"/>
			<extension name="smc"/>
			<extension name="sfc"/>
			<extension name="fig"/>
			<extension name="swc"/>
		</device>
	</machine>
	<machine name="snespal" sourcefile="snes.c" cloneof="snes" romof="snes">
		<description>Super Nintendo Entertainment System (PAL)</description>
		<year>1991</year>
		<manufacturer>Nintendo</manufacturer>
		<rom name="spc700.rom" merge="spc700.rom" size="64" crc="44bb3a40" sha1="97e352553e94242ae823547cd853eecda55c20f0" region="user5" offset="0"/>
		<rom name="dsp1data.bin" merge="dsp1data.bin" size="2048" crc="4b02d66d" sha1="1534f4403d2a0f68ba6e35186fe7595d33de34b1" region="user6" offset="0"/>
		<chip type="cpu" name="G65C816" clock="3580000"/>
		<chip type="cpu" name="SPC700" clock="1024000"/>
		<chip type="audio" name="Custom"/>
		<video screen="raster" orientation="horizontal" width="512" height="240" aspectx="4" aspecty="3" refresh="50.000000"/>
		<sound channels="2"/>
		<input players="4" control="joy8way" buttons="6"/>
		<driver status="imperfect" emulation="good" color="good" sound="imperfect" graphic="imperfect" savestate="unsupported" palettesize="32768"/>
		<device type="cartridge" mandatory="1">
			<instance name="cartridge" briefname="cart"/>
			<extension name="smc"/>
			<extension name="sfc"/>
			<extension name="fig"/>
			<extension name="swc"/>
		</device>
	</machine>
	<machine name="n64" sourcefile="n64.c">
		<description>Nintendo 64</description>
		<year>1996</year>
		<manufacturer>Nintendo</manufacturer>
		<chip type="cpu" name="R4600 (big)" clock="93750000"/>
		<chip type="cpu" name="RSP" clock="62500000"/>
		<chip type="audio" name="Custom"/>
		<video screen="raster" orientation="horizontal" width="640" height="480" aspectx="4" aspecty="3" refresh="60.000000"/>
		<sound channels="2"/>
		<input players="1" control="stick" buttons="9"/>
		<driver status="good" emulation="good" color="good" sound="good" graphic="good" savestate="unsupported" palettesize="4096"/>
		<device type="cartridge" mandatory="1">
			<instance name="cartridge" briefname="cart"/>
			<extension name="v64"/>
			<extension name="z64"/>
			<extension name="rom"/>
			<extension name="n64"/>
		</device>
	</machine>
	<machine name="megaduck" sourcefile="gb.c">
		<description>MegaDuck/Cougar Boy</description>
		<year>1993</year>
		<manufacturer>Creatronic/Videojet/Timlex/Cougar</manufacturer>
		<chip type="cpu" name="Z80GB" clock="4194304"/>
		<chip type="audio" name="Custom"/>
		<video screen="raster" orientation="horizontal" width="160" height="144" aspectx="4" aspecty="3" refresh="59.732155"/>
		<sound channels="2"/>
		<input players="1" control="joy8way" buttons="2"/>
		<driver status="good" emulation="good" color="good" sound="good" graphic="good" savestate="unsupported" palettesize="4"/>
		<device type="cartridge" mandatory="1">
			<instance name="cartridge" briefname="cart"/>
			<extension name="bin"/>
		</device>
	</machine>
	<machine name="gamegear" sourcefile="sms.c">
		<description>Sega Game Gear - European/American</description>
		<year>1990</year>
		<manufacturer>Sega</manufacturer>
		<biosset name="none" description="No BIOS" default="yes"/>
		<biosset name="majesco" description="Majesco BIOS"/>
		<rom name="majbios.rom" bios="majesco" size="1024" crc="0ebea9d4" sha1="914aa165e3d879f060be77870d345b60cfeb4ede" region="cpu1" offset="0"/>
		<chip type="cpu" name="Z80" clock="3597545"/>
		<chip type="audio" name="SN76496" clock="4194304"/>
		<video screen="raster" orientation="horizontal" width="160" height="144" aspectx="4" aspecty="3" refresh="60.000000"/>
		<sound channels="1"/>
		<input players="2" control="joy8way" buttons="2"/>
		<driver status="good" emulation="good" color="good" sound="good" graphic="good" savestate="unsupported" palettesize="32"/>
		<device type="cartridge" mandatory="1">
			<instance name="cartridge" briefname="cart"/>
			<extension name="gg"/>
		</device>
	</machine>
	<machine name="sms" sourcefile="sms.c">
		<description>Sega Master System/Sega Master System Plus/Sega Master System II</description>
		<year>1986</year>
		<manufacturer>Sega</manufacturer>
		<biosset name="bios13" description="US/European BIOS v1.3 (1986)" default="yes"/>
		<biosset name="hangonsh" description="US/European BIOS v2.4 with Hang On and Safari Hunt (1988)"/>
		<biosset name="hangon" description="US/European BIOS v3.4 with Hang On (1988)"/>
		<biosset name="alexkidd" description="US/European BIOS with Alex Kidd in Miracle World (1990)"/>
		<rom name="bios13fx.rom" bios="bios13" size="8192" crc="0072ed54" sha1="c315672807d8ddb8d91443729405c766dd95cae7" region="user1" offset="0"/>
		<rom name="sonbios.rom" bios="hangonsh" size="262144" crc="81c3476b" sha1="6aca0e3dffe461ba1cb11a86cd4caf5b97e1b8df" region="user1" offset="0"/>
		<rom name="hshbios.rom" bios="hangon" size="131072" crc="91e93385" sha1="9e179392cd416af14024d8f31c981d9ee9a64517" region="user1" offset="0"/>
		<rom name="hangbios.rom" bios="alexkidd" size="131072" crc="8edf7ac6" sha1="51fd6d7990f62cd9d18c9ecfc62ed7936169107e" region="user1" offset="0"/>
		<rom name="akbios.rom" size="131072" crc="cf4a09ea" sha1="3af7b66248d34eb26da40c92bf2fa4c73a46a051" region="user1" offset="0"/>
		<chip type="cpu" name="Z80" clock="3597545"/>
		<chip type="audio" name="SN76496" clock="4194304"/>
		<video screen="raster" orientation="horizontal" width="256" height="240" aspectx="4" aspecty="3" refresh="60.000000"/>
		<sound channels="1"/>
		<input players="2" control="joy8way" buttons="2"/>
		<driver status="good" emulation="good" color="good" sound="good" graphic="good" savestate="unsupported" palettesize="32"/>
		<device type="cartridge">
			<instance name="cartridge" briefname="cart"/>
			<extension name="sms"/>
		</device>
	</machine>
	<machine name="smspal" sourcefile="sms.c" cloneof="sms" romof="sms">
		<description>Sega Master System/Sega Master System Plus/Sega Master System II/Tec Toy Master System III Compact (Brazil)</description>
		<year>1986</year>
		<manufacturer>Sega</manufacturer>
		<biosset name="bios13" description="Sega Master System - US/European BIOS v1.3 (1986)" default="yes"/>
		<biosset name="hangonsh" description="Sega Master System Plus - US/European BIOS v2.4 with Hang On and Safari Hunt (1988)"/>
		<biosset name="hangon" description="Sega Master System - US/European BIOS v3.4 with Hang On (1988)"/>
		<biosset name="alexkidd" description="Sega Master System II - US/European BIOS with Alex Kidd in Miracle World (1990)"/>
		<biosset name="sonic" description="Sega Master System II/Tec Toy Master System III Compact (Brazil) - European/Brazilian BIOS with Sonic the Hedgehog (1991)"/>
		<rom name="bios13fx.rom" merge="bios13fx.rom" bios="bios13" size="8192" crc="0072ed54" sha1="c315672807d8ddb8d91443729405c766dd95cae7" region="user1" offset="0"/>
		<rom name="hshbios.rom" merge="hshbios.rom" bios="hangonsh" size="131072" crc="91e93385" sha1="9e179392cd416af14024d8f31c981d9ee9a64517" region="user1" offset="0"/>
		<rom name="hangbios.rom" merge="hangbios.rom" bios="hangon" size="131072" crc="8edf7ac6" sha1="51fd6d7990f62cd9d18c9ecfc62ed7936169107e" region="user1" offset="0"/>
		<rom name="akbios.rom" merge="akbios.rom" bios="alexkidd" size="131072" crc="cf4a09ea" sha1="3af7b66248d34eb26da40c92bf2fa4c73a46a051" region="user1" offset="0"/>
		<rom name="sonbios.rom" merge="sonbios.rom" bios="sonic" size="262144" crc="81c3476b" sha1="6aca0e3dffe461ba1cb11a86cd4caf5b97e1b8df" region="user1" offset="0"/>
		<chip type="cpu" name="Z80" clock="3597545"/>
		<chip type="audio" name="SN76496" clock="4194304"/>
		<video screen="raster" orientation="horizontal" width="256" height="240" aspectx="4" aspecty="3" refresh="50.000000"/>
		<sound channels="1"/>
		<input players="2" control="joy8way" buttons="2"/>
		<driver status="good" emulation="good" color="good" sound="good" graphic="good" savestate="unsupported" palettesize="32"/>
		<device type="cartridge">
			<instance name="cartridge" briefname="cart"/>
			<extension name="sms"/>
		</device>
	</machine>
	<machine name="smsj21" sourcefile="sms.c" cloneof="smsm3" romof="smsm3">
		<description>Sega Master System/Samsung Gamboy</description>
		<year>1985</year>
		<manufacturer>Sega</manufacturer>
		<biosset name="jbios21" description="Sega Mark III/Sega Master System/Samsung Gamboy - Japanese SMS BIOS v2.1" default="yes"/>